// src/components/Gallery/galleryData.js
export const galleryData = {
  interior: {
    title: "Interior Painting",
    description:
      "Our skilled team brings a touch of artistry to your space, transforming it into a masterpiece. Explore our top-notch interior painting solutions, blending style and quality.",
    services: [
      "Preparation: caulking, filling and spackling, sanding, masking and covering surfaces",
      "Minor drywall repair",
      "Brush & roll, spray finish",
      "Painting walls & ceilings",
      "Painting trims and doors",
    ],
    images: [
      "/assets/img/interior/image1.jpg",
      "/assets/img/interior/image2.jpg",
      "/assets/img/interior/image3.jpg",
      "/assets/img/interior/image4.jpg",
      "/assets/img/interior/image5.jpg",
      "/assets/img/interior/image6.jpg",
      "/assets/img/interior/image7.jpg",
      "/assets/img/interior/image8.jpg",
      "/assets/img/interior/image9.jpg",
      "/assets/img/interior/image10.jpg",
      "/assets/img/interior/image11.jpg",
      "/assets/img/interior/image12.jpg",
      "/assets/img/interior/image13.jpg",
      "/assets/img/interior/image14.jpg",
      "/assets/img/interior/image15.jpg",
    ],
  },
  exterior: {
    title: "Exterior Painting",
    description:
      "Our skilled team delivers precision and quality that lasts. Enhance curb appeal and protect your investment. Explore vibrant color options and durable finishes.",
    services: [
      "Preparation: caulking, scraping, sanding, priming",
      "Pressure wash",
      "Paint hardie, wood, vinyl, aluminum siding, stucco",
      "Paint exterior trim and door",
      "Apply solid, semi-solid and semi-transparent stain",
    ],
    images: [
      "/assets/img/exterior/image1.jpg",
      "/assets/img/exterior/image2.jpg",
      "/assets/img/exterior/image3.jpg",
      "/assets/img/exterior/image4.jpg",
      "/assets/img/exterior/image5.jpg",
      "/assets/img/exterior/image6.jpg",
      "/assets/img/exterior/image7.jpg",
      "/assets/img/exterior/image8.jpg",
      "/assets/img/exterior/image9.jpg",
      "/assets/img/exterior/image10.jpg",
      "/assets/img/exterior/image11.jpg",
      "/assets/img/exterior/image12.jpg",
      "/assets/img/exterior/image13.jpg",
      "/assets/img/exterior/image14.jpg",
    ],
  },
  cabinets: {
    title: "Cabinet Painting",
    description:
      "Transform your cabinets with expert painting and refinishing. We provide high-quality cabinet painting services that will enhance the appearance of your kitchen, bathroom, and more.",
    services: [
      "Cabinet sanding and refinishing",
      "Expert color matching and custom finishes",
      "Quick turnaround times",
      "Protection of surrounding areas",
    ],
    images: [
      "/assets/img/cabinet/image1.jpg",
      "/assets/img/cabinet/image2.jpg",
      "/assets/img/cabinet/image3.jpg",
      "/assets/img/cabinet/image4.jpg",
      "/assets/img/cabinet/image5.jpg",
      "/assets/img/cabinet/image6.jpg",
      "/assets/img/cabinet/image7.jpg",
      "/assets/img/cabinet/image8.jpg",
      "/assets/img/cabinet/image9.jpg",
      "/assets/img/cabinet/image10.jpg",
      "/assets/img/cabinet/image11.jpg",
      "/assets/img/cabinet/image12.jpg",
      "/assets/img/cabinet/image13.jpg",
      "/assets/img/cabinet/image14.jpg",
      "/assets/img/cabinet/image15.jpg",
    ],
  },
  deckAndFence: {
    title: "Deck & Fence Painting",
    description:
      "Protect and enhance your outdoor spaces with our professional deck and fence painting services. Our team offers expert staining and finishing for lasting beauty and durability.",
    services: [
      "Pressure washing and surface preparation",
      "Custom staining and finishing",
      "Long-lasting protection against the elements",
    ],
    images: [
      "/assets/img/deck_fence/image1.jpg",
      "/assets/img/deck_fence/image2.jpg",
      "/assets/img/deck_fence/image3.jpg",
      "/assets/img/deck_fence/image4.jpg",
      "/assets/img/deck_fence/image5.jpg",
      "/assets/img/deck_fence/image6.jpg",
      "/assets/img/deck_fence/image7.jpg",
      "/assets/img/deck_fence/image8.jpg",
      "/assets/img/deck_fence/image9.jpg",
      "/assets/img/deck_fence/image10.jpg",
      "/assets/img/deck_fence/image11.jpg",
      "/assets/img/deck_fence/image12.jpg",
      "/assets/img/deck_fence/image13.jpg",
      "/assets/img/deck_fence/image14.jpg",
      "/assets/img/deck_fence/image15.jpg",
    ],
  },
};
